name: ğŸSony Liv PlaylistğŸ‘

on:
  schedule:
    - cron: '0/5 * * * *'   # every 6 hours
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download M3U file
        run: |
          mkdir -p playlists
          curl -L "https://nonyliv.saqlainhaider8198.workers.dev/nony2.m3u" \
            -o playlist/liv.m3u

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add playlist/liv.m3u
          git commit -m "Auto update liv.m3u" || echo "No changes"
          git push
