name: Run Python Script
on:
  schedule:
    - cron: '0 0 * * *' #Tamilott daily Json Generator
  workflow_dispatch:
  push:
    branches:
      - main # or your default branch name

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to access your code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to install Python
      with:
        python-version: '3.10' # Specify the desired Python version

    - name: Install dependencies (if any)
      run: pip install -r requirements.txt # Installs packages from requirements.txt

    - name: Execute Python script
      run: python test.py # Runs your Python script
      
