name: M3U to JSON Converter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'   # every 6 hours

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Download M3U playlist with headers
        run: |
          mkdir -p data
          curl -L \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0" \
            -H "Cache-Control: no-cache, no-store" \
            "https://zee5.cloud-hatchh.workers.dev/?token=42e4f5-2d413b-3c37d8-7f3f25" \
            -o data/input.m3u

      - name: Convert M3U to JSON (split headers)
        run: |
          python script/m3u_to_json/zee5jsoncon.py

      - name: Commit & Push output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add playlist/zee5.m3u json/zee5.json
          git commit -m "Auto convert M3U to JSON" || echo "No changes"
          git push
